# -*- coding: utf-8 -*-
from odoo import fields, models, _
from odoo.exceptions import UserError


class AccountMove(models.Model):
    _inherit = 'account.move'

    subscription_order_id = fields.Many2one(
        'sale.order', string='Subscription', readonly=True, copy=False, index=True,
        help="Subscription this invoice was generated from (or linked to).")
    subscription_linked_manually = fields.Boolean(
        string='Manually Linked to Subscription', readonly=True, copy=False,
        help="True when this invoice was attached to a subscription by hand "
             "(historical/migrated invoice), not generated by the billing engine.")
    subscription_period_start = fields.Date(string='Covered Period Start', copy=False)
    subscription_period_end = fields.Date(string='Covered Period End', copy=False)

    def action_unlink_from_subscription(self):
        for move in self:
            if not move.subscription_order_id:
                continue
            if not move.subscription_linked_manually:
                raise UserError(_(
                    "Invoice %s was generated by the billing engine and cannot be "
                    "detached. Only manually-linked historical invoices can be "
                    "unlinked.", move.name))
            order = move.subscription_order_id
            move.sudo().write({
                'subscription_order_id': False,
                'subscription_linked_manually': False,
                'subscription_period_start': False,
                'subscription_period_end': False,
            })
            order.message_post(body=_("Unlinked historical invoice %s.", move.name))
        return True
